unit Entity.Produto;

interface

uses MVCFramework.ActiveRecord,MVCFramework.SQLGenerators.MSSQL;

type
  [MVCTable('produto')]
  TProduto = class(TMVCActiveRecord)
  private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Integer;
    [MVCTableField('nome')]
    FNome: string;
    [MVCTableField('descricao')]
    FDescricao: string;
    [MVCTableField('preco')]
    FPreco: Double;
  public
    property id: Integer read FID write FID;
    property nome: string read FNome write FNome;
    property descricao: string read FDescricao write FDescricao;
    property preco: Double read FPreco write FPreco;
  end;

implementation

{ TProduto }

end.
